package com.example.receipt.monster;

import com.example.receipt.monster.MonsterViews.BattleView;
import com.example.receipt.monster.MonsterViews.ReceiptView;
import com.example.receipt.monster.engine.MonsterCard;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;

import java.sql.Timestamp;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/** monster_room／monster_play／monster_battle テーブル。 */
@Repository
public class MonsterRoomRepository {
    private static final Gson GSON = new Gson();

    private final JdbcTemplate jdbc;

    public MonsterRoomRepository(JdbcTemplate jdbc) {
        this.jdbc = jdbc;
    }

    public record Room(long id, String code, String status, String mode, int round, String p1TokenHash, String p2TokenHash,
                       Instant p1SeenAt, Instant p2SeenAt, Instant waitDeadline, Instant expiresAt, String cpuReason,
                       String notice, String closedBy) {
    }

    /** 配布したレシート。表示内容はプレイ中だけの一時コピー。 */
    public record FieldEntry(long cardId, ReceiptView receipt) {
    }

    public record Play(long id, long roomId, String seat, List<FieldEntry> field, List<Long> hand, List<Integer> flipped,
                       Long imageCardId, ReceiptView imageReceipt, MonsterCard selected, boolean confirmed) {
        public Play withField(List<FieldEntry> newField, List<Integer> newFlipped) {
            return new Play(id, roomId, seat, newField, hand, newFlipped, imageCardId, imageReceipt, selected, confirmed);
        }

        public Play withHand(List<Long> newHand, List<Integer> newFlipped) {
            return new Play(id, roomId, seat, field, newHand, newFlipped, imageCardId, imageReceipt, selected, confirmed);
        }

        public Play withImage(Long cardId, ReceiptView receipt) {
            return new Play(id, roomId, seat, field, hand, flipped, cardId, receipt, selected, confirmed);
        }

        public Play withSelected(MonsterCard card) {
            return new Play(id, roomId, seat, field, hand, flipped, imageCardId, imageReceipt, card, card != null);
        }

        public List<Long> fieldCardIds() {
            return field.stream().map(FieldEntry::cardId).toList();
        }
    }

    public void ensureSchema() {
        jdbc.execute("""
                CREATE TABLE IF NOT EXISTS monster_room (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                code VARCHAR(6) NOT NULL UNIQUE, status VARCHAR(16) NOT NULL, mode VARCHAR(8) NOT NULL,
                round_no INTEGER NOT NULL DEFAULT 0, p1_token_hash VARCHAR(64) NOT NULL, p2_token_hash VARCHAR(64),
                p1_seen_at TIMESTAMP WITH TIME ZONE, p2_seen_at TIMESTAMP WITH TIME ZONE,
                wait_deadline TIMESTAMP WITH TIME ZONE NOT NULL, expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
                cpu_reason VARCHAR(100), notice VARCHAR(200), closed_by VARCHAR(2),
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP)
                """);
        jdbc.execute("""
                CREATE TABLE IF NOT EXISTS monster_play (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                room_id BIGINT NOT NULL REFERENCES monster_room(id) ON DELETE CASCADE,
                seat VARCHAR(2) NOT NULL, field_json TEXT NOT NULL, hand_json TEXT NOT NULL, flipped_json TEXT NOT NULL,
                image_card_id BIGINT, image_receipt_json TEXT, selected_card_json TEXT, confirmed BOOLEAN NOT NULL,
                UNIQUE (room_id, seat))
                """);
        jdbc.execute("""
                CREATE TABLE IF NOT EXISTS monster_battle (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                room_id BIGINT NOT NULL REFERENCES monster_room(id) ON DELETE CASCADE,
                round_no INTEGER NOT NULL, battle_seed BIGINT NOT NULL, winner VARCHAR(4) NOT NULL, reason VARCHAR(8) NOT NULL,
                result_json TEXT NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                UNIQUE (room_id, round_no))
                """);
    }

    private static final RowMapper<Room> ROOM = (rs, n) -> new Room(rs.getLong("id"), rs.getString("code"),
            rs.getString("status"), rs.getString("mode"), rs.getInt("round_no"), rs.getString("p1_token_hash"),
            rs.getString("p2_token_hash"), instant(rs.getTimestamp("p1_seen_at")), instant(rs.getTimestamp("p2_seen_at")),
            instant(rs.getTimestamp("wait_deadline")), instant(rs.getTimestamp("expires_at")), rs.getString("cpu_reason"),
            rs.getString("notice"), rs.getString("closed_by"));

    private static final RowMapper<Play> PLAY = (rs, n) -> new Play(rs.getLong("id"), rs.getLong("room_id"),
            rs.getString("seat"),
            GSON.fromJson(rs.getString("field_json"), new TypeToken<List<FieldEntry>>() { }.getType()),
            GSON.fromJson(rs.getString("hand_json"), new TypeToken<List<Long>>() { }.getType()),
            GSON.fromJson(rs.getString("flipped_json"), new TypeToken<List<Integer>>() { }.getType()),
            (Long) rs.getObject("image_card_id", Long.class),
            GSON.fromJson(rs.getString("image_receipt_json"), ReceiptView.class),
            GSON.fromJson(rs.getString("selected_card_json"), MonsterCard.class),
            rs.getBoolean("confirmed"));

    public boolean codeExists(String code) {
        Integer count = jdbc.queryForObject("SELECT COUNT(*) FROM monster_room WHERE code = ?", Integer.class, code);
        return count != null && count > 0;
    }

    public long insertRoom(String code, String p1TokenHash, Instant now, Instant waitDeadline, Instant expiresAt) {
        jdbc.update("INSERT INTO monster_room (code, status, mode, round_no, p1_token_hash, p1_seen_at, wait_deadline, expires_at) "
                        + "VALUES (?, 'WAITING', 'HUMAN', 0, ?, ?, ?, ?)",
                code, p1TokenHash, ts(now), ts(waitDeadline), ts(expiresAt));
        long id = jdbc.queryForObject("SELECT id FROM monster_room WHERE code = ?", Long.class, code);
        for (String seat : List.of("P1", "P2")) {
            jdbc.update("INSERT INTO monster_play (room_id, seat, field_json, hand_json, flipped_json, confirmed) "
                    + "VALUES (?, ?, '[]', '[]', '[]', FALSE)", id, seat);
        }
        return id;
    }

    /** 行ロックを取ってルームを読む（同じルームへの操作を順番に処理する）。 */
    public Optional<Room> lockByCode(String code) {
        return jdbc.query("SELECT * FROM monster_room WHERE code = ? FOR UPDATE", ROOM, code).stream().findFirst();
    }

    public void updateRoom(Room r) {
        jdbc.update("UPDATE monster_room SET status = ?, mode = ?, round_no = ?, p2_token_hash = ?, p1_seen_at = ?, "
                        + "p2_seen_at = ?, expires_at = ?, cpu_reason = ?, notice = ?, closed_by = ? WHERE id = ?",
                r.status(), r.mode(), r.round(), r.p2TokenHash(), ts(r.p1SeenAt()), ts(r.p2SeenAt()), ts(r.expiresAt()),
                r.cpuReason(), r.notice(), r.closedBy(), r.id());
    }

    public Play play(long roomId, String seat) {
        return jdbc.queryForObject("SELECT * FROM monster_play WHERE room_id = ? AND seat = ?", PLAY, roomId, seat);
    }

    public void savePlay(Play p) {
        jdbc.update("UPDATE monster_play SET field_json = ?, hand_json = ?, flipped_json = ?, image_card_id = ?, "
                        + "image_receipt_json = ?, selected_card_json = ?, confirmed = ? WHERE id = ?",
                GSON.toJson(p.field()), GSON.toJson(p.hand()), GSON.toJson(p.flipped()), p.imageCardId(),
                p.imageReceipt() == null ? null : GSON.toJson(p.imageReceipt()),
                p.selected() == null ? null : GSON.toJson(p.selected()), p.confirmed(), p.id());
    }

    /** 配り直し・終了時に、プレイ用のレシートのコピーを消す。 */
    public void resetPlay(long roomId, String seat, List<FieldEntry> field) {
        jdbc.update("UPDATE monster_play SET field_json = ?, hand_json = '[]', flipped_json = '[]', image_card_id = NULL, "
                + "image_receipt_json = NULL, selected_card_json = NULL, confirmed = FALSE WHERE room_id = ? AND seat = ?",
                GSON.toJson(field == null ? new ArrayList<>() : field), roomId, seat);
    }

    public void insertBattle(long roomId, int round, BattleView battle) {
        jdbc.update("INSERT INTO monster_battle (room_id, round_no, battle_seed, winner, reason, result_json) VALUES (?, ?, ?, ?, ?, ?)",
                roomId, round, battle.battleSeed(), battle.winner(), battle.reason(), GSON.toJson(battle));
    }

    public Optional<BattleView> battle(long roomId, int round) {
        return jdbc.queryForList("SELECT result_json FROM monster_battle WHERE room_id = ? AND round_no = ?", String.class,
                roomId, round).stream().findFirst().map(json -> GSON.fromJson(json, BattleView.class));
    }

    public void deleteBattles(long roomId) {
        jdbc.update("DELETE FROM monster_battle WHERE room_id = ?", roomId);
    }

    /** 期限切れのルームを消す（プレイ・対戦も連動して消える）。閉じたルームは期限を短くしてある。 */
    public int deleteExpired(Instant now) {
        return jdbc.update("DELETE FROM monster_room WHERE expires_at < ?", ts(now));
    }

    private static Timestamp ts(Instant instant) {
        return instant == null ? null : Timestamp.from(instant);
    }

    private static Instant instant(Timestamp ts) {
        return ts == null ? null : ts.toInstant();
    }
}
