package com.example.receipt.monster;

import com.example.receipt.dto.ReceiptItemData;
import com.example.receipt.dto.ReceiptStructuredData;
import com.example.receipt.monster.engine.MonsterCard;
import com.example.receipt.repository.ReceiptTableName;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;

import java.sql.Timestamp;
import java.time.Instant;
import java.util.List;
import java.util.Optional;

/**
 * monster_card テーブル。レシートの行テキスト・表示内容は保存しない。
 * レシートの削除との連動は {@link com.example.receipt.repository.ReceiptTableRepository#deleteReceipt} で行う
 * （既存の receipt_structured_summary に外部キーを張ると、既存の DROP TABLE が失敗するため）。
 */
@Repository
public class MonsterCardRepository {
    public static final String DRAFT = "DRAFT";
    public static final String ACTIVE = "ACTIVE";

    private final JdbcTemplate jdbc;

    public MonsterCardRepository(JdbcTemplate jdbc) {
        this.jdbc = jdbc;
    }

    public record StoredCard(MonsterCard card, String status, String receiptTableName) {
    }

    private static final String COLUMNS = "id, image_sha256, source, name, element, rarity, hp, atk, defense, spd, luck, power, "
            + "skill_name, skill_power, lucky, flavor, store_category, svg, algorithm_version, status, receipt_table_name";

    private static final RowMapper<StoredCard> MAPPER = (rs, rowNum) -> new StoredCard(new MonsterCard(
            rs.getLong("id"), rs.getString("image_sha256"), rs.getString("source"), rs.getString("name"),
            rs.getString("element"), rs.getString("rarity"), rs.getInt("hp"), rs.getInt("atk"), rs.getInt("defense"),
            rs.getInt("spd"), rs.getInt("luck"), rs.getInt("power"), rs.getString("skill_name"), rs.getDouble("skill_power"),
            rs.getBoolean("lucky"), rs.getString("flavor"), rs.getString("store_category"), rs.getString("svg"),
            rs.getInt("algorithm_version")), rs.getString("status"), rs.getString("receipt_table_name"));

    public void ensureSchema() {
        jdbc.execute("""
                CREATE TABLE IF NOT EXISTS monster_card (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                receipt_table_name VARCHAR(64) UNIQUE,
                image_sha256 VARCHAR(64) NOT NULL UNIQUE,
                status VARCHAR(16) NOT NULL,
                source VARCHAR(16) NOT NULL,
                name VARCHAR(64) NOT NULL, element VARCHAR(8) NOT NULL, rarity VARCHAR(8) NOT NULL,
                hp INTEGER NOT NULL, atk INTEGER NOT NULL, defense INTEGER NOT NULL, spd INTEGER NOT NULL,
                luck INTEGER NOT NULL, power INTEGER NOT NULL,
                skill_name VARCHAR(64) NOT NULL, skill_power DOUBLE PRECISION NOT NULL, lucky BOOLEAN NOT NULL,
                flavor VARCHAR(255), store_category VARCHAR(50), svg TEXT NOT NULL, algorithm_version INTEGER NOT NULL,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                activated_at TIMESTAMP WITH TIME ZONE)
                """);
    }

    public Optional<StoredCard> findBySha(String sha256) {
        return jdbc.query("SELECT " + COLUMNS + " FROM monster_card WHERE image_sha256 = ?", MAPPER, sha256).stream().findFirst();
    }

    public Optional<StoredCard> findById(long id) {
        return jdbc.query("SELECT " + COLUMNS + " FROM monster_card WHERE id = ?", MAPPER, id).stream().findFirst();
    }

    /** 下書きを作る。同じ画像のカードが既にあれば、それを返す。 */
    public StoredCard insertDraft(MonsterCard card) {
        Optional<StoredCard> existing = findBySha(card.imageSha256());
        if (existing.isPresent()) return existing.get();
        try {
            insert(card, DRAFT, null);
        } catch (DuplicateKeyException e) {
            // 同時に作られた場合は先に入った方を使う
        }
        return findBySha(card.imageSha256()).orElseThrow();
    }

    /** 保存されたレシートのカードを有効にする。下書きがあれば、このカードの内容（イラストを含む）で上書きする。 */
    public StoredCard activate(MonsterCard card, String receiptTableName) {
        Optional<StoredCard> existing = findBySha(card.imageSha256());
        if (existing.isEmpty()) {
            insert(card, ACTIVE, receiptTableName);
        } else {
            jdbc.update("UPDATE monster_card SET status = ?, receipt_table_name = ?, name = ?, element = ?, rarity = ?, "
                            + "hp = ?, atk = ?, defense = ?, spd = ?, luck = ?, power = ?, skill_name = ?, skill_power = ?, "
                            + "lucky = ?, flavor = ?, store_category = ?, svg = ?, algorithm_version = ?, activated_at = CURRENT_TIMESTAMP "
                            + "WHERE id = ?",
                    ACTIVE, receiptTableName, card.name(), card.element(), card.rarity(), card.hp(), card.atk(), card.def(),
                    card.spd(), card.luck(), card.power(), card.skillName(), card.skillPower(), card.lucky(), card.flavor(),
                    card.storeCategory(), card.svg(), card.algorithmVersion(), existing.get().card().id());
        }
        return findBySha(card.imageSha256()).orElseThrow();
    }

    public void updateSvg(long id, String svg) {
        jdbc.update("UPDATE monster_card SET svg = ? WHERE id = ?", svg, id);
    }

    private void insert(MonsterCard card, String status, String receiptTableName) {
        jdbc.update("INSERT INTO monster_card (image_sha256, status, source, receipt_table_name, name, element, rarity, hp, atk, "
                        + "defense, spd, luck, power, skill_name, skill_power, lucky, flavor, store_category, svg, algorithm_version, "
                        + "activated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
                card.imageSha256(), status, card.source(), receiptTableName, card.name(), card.element(), card.rarity(),
                card.hp(), card.atk(), card.def(), card.spd(), card.luck(), card.power(), card.skillName(), card.skillPower(),
                card.lucky(), card.flavor(), card.storeCategory(), card.svg(), card.algorithmVersion(),
                ACTIVE.equals(status) ? Timestamp.from(Instant.now()) : null);
    }

    public int deleteByReceiptTable(String receiptTableName) {
        return jdbc.update("DELETE FROM monster_card WHERE receipt_table_name = ?", receiptTableName);
    }

    public int deleteDraftsCreatedBefore(Instant cutoff) {
        return jdbc.update("DELETE FROM monster_card WHERE status = ? AND created_at < ?", DRAFT, Timestamp.from(cutoff));
    }

    /** 対戦に使える有効なカードのID（元レシートが残っているものだけ）。 */
    public List<Long> activeCardIds() {
        if (!tableExists("receipt_structured_summary")) return List.of();
        return jdbc.queryForList("SELECT c.id FROM monster_card c JOIN receipt_structured_summary s "
                + "ON s.receipt_table_name = c.receipt_table_name WHERE c.status = ? ORDER BY c.id", Long.class, ACTIVE);
    }

    public long countAll() {
        Long count = jdbc.queryForObject("SELECT COUNT(*) FROM monster_card", Long.class);
        return count == null ? 0 : count;
    }

    /** 保存済みのレシート（古い順）。 */
    public List<String> savedReceiptTables() {
        if (!tableExists("receipt_structured_summary")) return List.of();
        return jdbc.queryForList("SELECT receipt_table_name FROM receipt_structured_summary ORDER BY id", String.class);
    }

    /** カードを持たない保存済みレシート（機能追加前のもの）。 */
    public List<String> receiptTablesWithoutCard() {
        if (!tableExists("receipt_structured_summary")) return List.of();
        return jdbc.queryForList("SELECT s.receipt_table_name FROM receipt_structured_summary s "
                + "LEFT JOIN monster_card c ON c.receipt_table_name = s.receipt_table_name WHERE c.id IS NULL", String.class);
    }

    public Optional<String> imageShaOfReceipt(String receiptTableName) {
        return jdbc.queryForList("SELECT image_sha256 FROM receipt_structured_summary WHERE receipt_table_name = ?",
                String.class, receiptTableName).stream().findFirst();
    }

    /** 既存の構造化データを読む（表示用・カード生成用）。 */
    public Optional<ReceiptStructuredData> loadReceipt(String receiptTableName) {
        if (receiptTableName == null || !tableExists("receipt_structured_summary")) return Optional.empty();
        List<ReceiptStructuredData> rows = jdbc.query("SELECT store_name, branch_name, store_category, purchased_at, total_amount, "
                        + "payment_method, receipt_number FROM receipt_structured_summary WHERE receipt_table_name = ?",
                (rs, n) -> {
                    Timestamp purchased = rs.getTimestamp("purchased_at");
                    long total = rs.getLong("total_amount");
                    return new ReceiptStructuredData(rs.getString("store_name"), rs.getString("branch_name"),
                            rs.getString("store_category"), purchased == null ? null : purchased.toLocalDateTime(),
                            rs.wasNull() ? null : total, rs.getString("payment_method"), rs.getString("receipt_number"), List.of());
                }, receiptTableName);
        if (rows.isEmpty()) return Optional.empty();
        ReceiptStructuredData s = rows.getFirst();
        List<ReceiptItemData> items = tableExists("receipt_structured_item")
                ? jdbc.query("SELECT item_name, category, quantity, unit_price, amount FROM receipt_structured_item "
                        + "WHERE receipt_table_name = ? ORDER BY item_no", (rs, n) -> new ReceiptItemData(
                        rs.getString("item_name"), rs.getString("category"), rs.getBigDecimal("quantity"),
                        nullableLong(rs.getObject("unit_price")), nullableLong(rs.getObject("amount"))), receiptTableName)
                : List.of();
        return Optional.of(new ReceiptStructuredData(s.storeName(), s.branchName(), s.storeCategory(), s.purchasedAt(),
                s.totalAmount(), s.paymentMethod(), s.receiptNumber(), items));
    }

    /** 再点検で個人情報を取り除いた自由記述の項目を書き戻す。 */
    public void updateReceiptText(String receiptTableName, ReceiptStructuredData data) {
        jdbc.update("UPDATE receipt_structured_summary SET store_name = ?, branch_name = ?, payment_method = ? WHERE receipt_table_name = ?",
                data.storeName(), data.branchName(), data.paymentMethod(), receiptTableName);
        int no = 0;
        for (ReceiptItemData item : data.safeItems()) {
            no++;
            jdbc.update("UPDATE receipt_structured_item SET item_name = ? WHERE receipt_table_name = ? AND item_no = ?",
                    item.name(), receiptTableName, no);
        }
    }

    public List<String> receiptLines(String receiptTableName) {
        if (!ReceiptTableName.isSafe(receiptTableName)) throw new IllegalArgumentException("unsafe table name");
        return jdbc.queryForList("SELECT text FROM " + receiptTableName + " ORDER BY line_no", String.class);
    }

    public boolean tableExists(String tableName) {
        Integer count = jdbc.queryForObject("SELECT COUNT(*) FROM information_schema.tables "
                + "WHERE LOWER(table_schema) = 'public' AND LOWER(table_name) = LOWER(?)", Integer.class, tableName);
        return count != null && count > 0;
    }

    private static Long nullableLong(Object value) {
        return value == null ? null : ((Number) value).longValue();
    }
}
