logging:
  file:
    name: log/backend.log
  logback:
    rollingpolicy:
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.zip"

server:
  servlet:
    session:
      cookie:
        secure: false

app:
  auth:
    cookie-secure: false

