package com.example.receipt.repository;

import com.example.receipt.dto.ReceiptDetail;
import com.example.receipt.dto.ReceiptLine;
import com.example.receipt.dto.ReceiptSummary;
import com.example.receipt.dto.ReceiptStructuredData;
import com.example.receipt.dto.ReceiptItemData;
import com.example.receipt.exception.ReceiptException;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.BatchPreparedStatementSetter;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.springframework.dao.DuplicateKeyException;

@Repository
public class ReceiptTableRepository {
    private static final String STRUCTURED_ITEM_SUMMARY_FK = "fk_receipt_structured_item_summary";

    private final JdbcTemplate jdbcTemplate;

    public ReceiptTableRepository(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    public String createReceiptTableAndInsert(List<String> lines) {
        String tableName = ReceiptTableName.generate();
        return createReceiptTableAndInsert(tableName, lines);
    }

    public String createReceiptTableAndInsert(List<String> lines, String sha256) {
        ensureImageHashRegistry();
        String tableName = ReceiptTableName.generate();
        int updated = jdbcTemplate.update(
                "UPDATE receipt_image_hash_registry SET table_name = ? " +
                        "WHERE image_sha256 = ? AND table_name IS NULL",
                tableName,
                sha256
        );
        if (updated == 0) {
            throw new ReceiptException(HttpStatus.CONFLICT, "DUPLICATE_RECEIPT_IMAGE", "同じレシート画像は既に登録されています。");
        }
        return createReceiptTableAndInsert(tableName, lines);
    }

    public void reserveImageHash(String sha256) {
        ensureImageHashRegistry();

        List<String> registeredTables = jdbcTemplate.query(
                "SELECT table_name FROM receipt_image_hash_registry WHERE image_sha256 = ?",
                (rs, rowNum) -> rs.getString("table_name"),
                sha256
        );
        if (!registeredTables.isEmpty() && registeredTables.getFirst() != null) {
            throw duplicateReceiptImage();
        }

        try {
            int inserted = jdbcTemplate.update(
                    "INSERT INTO receipt_image_hash_registry (image_sha256, table_name) VALUES (?, NULL)",
                    sha256
            );
            if (inserted == 1) {
                return;
            }
        } catch (DuplicateKeyException e) {
            // 別リクエストが解析中に確保した未登録ハッシュなら再解析を許可する。
            List<String> currentTables = jdbcTemplate.query(
                    "SELECT table_name FROM receipt_image_hash_registry WHERE image_sha256 = ?",
                    (rs, rowNum) -> rs.getString("table_name"),
                    sha256
            );
            if (!currentTables.isEmpty() && currentTables.getFirst() == null) {
                return;
            }
            throw duplicateReceiptImage();
        }
    }

    private ReceiptException duplicateReceiptImage() {
        return new ReceiptException(
                HttpStatus.CONFLICT,
                "DUPLICATE_RECEIPT_IMAGE",
                "同じレシート画像は既にPostgreSQLへ登録されています。"
        );
    }

    public String createReceiptTableAndInsert(String tableName, List<String> lines) {
        assertSafeTableName(tableName);

        String createSql = """
                CREATE TABLE %s (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    line_no INTEGER NOT NULL,
                    text TEXT NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """.formatted(tableName);

        jdbcTemplate.execute(createSql);

        String insertSql = "INSERT INTO " + tableName + " (line_no, text) VALUES (?, ?)";
        jdbcTemplate.batchUpdate(insertSql, new BatchPreparedStatementSetter() {
            @Override
            public void setValues(PreparedStatement ps, int i) throws SQLException {
                ps.setInt(1, i + 1);
                ps.setString(2, lines.get(i));
            }

            @Override
            public int getBatchSize() {
                return lines.size();
            }
        });

        return tableName;
    }

    public void saveStructuredData(String tableName, String sha256, ReceiptStructuredData data) {
        ensureStructuredDataTables();
        if (data == null) data = new ReceiptStructuredData(null, null, "その他", null, null, null, null, List.of());
        jdbcTemplate.update("INSERT INTO receipt_structured_summary (receipt_table_name,image_sha256,store_name,branch_name,store_category,purchased_at,total_amount,payment_method,receipt_number) VALUES (?,?,?,?,?,?,?,?,?)",
                tableName, sha256, data.storeName(), data.branchName(), data.storeCategory(), data.purchasedAt(), data.totalAmount(), data.paymentMethod(), data.receiptNumber());
        int number = 0;
        for (ReceiptItemData item : data.safeItems()) {
            if (item == null || item.name() == null || item.name().isBlank()) continue;
            jdbcTemplate.update("INSERT INTO receipt_structured_item (receipt_table_name,item_no,item_name,category,quantity,unit_price,amount) VALUES (?,?,?,?,?,?,?)",
                    tableName, ++number, item.name(), item.category() == null ? "その他" : item.category(), item.quantity(), item.unitPrice(), item.amount());
        }
    }

    private void ensureStructuredDataTables() {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS receipt_structured_summary (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, receipt_table_name VARCHAR(64) NOT NULL UNIQUE,
                image_sha256 VARCHAR(64) NOT NULL UNIQUE, store_name VARCHAR(255), branch_name VARCHAR(255),
                store_category VARCHAR(50), purchased_at TIMESTAMP, total_amount BIGINT, payment_method VARCHAR(100),
                receipt_number VARCHAR(100), created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP)
                """);
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS receipt_structured_item (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, receipt_table_name VARCHAR(64) NOT NULL,
                item_no INTEGER NOT NULL, item_name TEXT NOT NULL, category VARCHAR(50) NOT NULL, quantity NUMERIC(12,3),
                unit_price BIGINT, amount BIGINT, created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                UNIQUE (receipt_table_name, item_no))
                """);
        jdbcTemplate.update("DELETE FROM receipt_structured_item " +
                "WHERE receipt_table_name NOT IN (SELECT receipt_table_name FROM receipt_structured_summary)");
        if (!structuredItemSummaryForeignKeyExists()) {
            jdbcTemplate.execute("ALTER TABLE receipt_structured_item ADD CONSTRAINT " + STRUCTURED_ITEM_SUMMARY_FK +
                    " FOREIGN KEY (receipt_table_name) REFERENCES receipt_structured_summary(receipt_table_name) ON DELETE CASCADE");
        }
    }

    private boolean structuredItemSummaryForeignKeyExists() {
        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM information_schema.table_constraints " +
                        "WHERE LOWER(table_schema) = 'public' AND LOWER(table_name) = 'receipt_structured_item' " +
                        "AND LOWER(constraint_name) = LOWER(?)",
                Integer.class,
                STRUCTURED_ITEM_SUMMARY_FK
        );
        return count != null && count > 0;
    }

    private void ensureImageHashRegistry() {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS receipt_image_hash_registry (
                    image_sha256 VARCHAR(64) PRIMARY KEY,
                    table_name VARCHAR(64) UNIQUE,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbcTemplate.execute("ALTER TABLE receipt_image_hash_registry ALTER COLUMN table_name DROP NOT NULL");
    }

    public List<ReceiptSummary> findAllReceiptTables() {
        List<ReceiptSummary> summaries = new ArrayList<>();
        for (String tableName : findReceiptTableNames()) {
            summaries.add(summaryFor(tableName));
        }
        return summaries;
    }

    public ReceiptDetail findReceipt(String tableName) {
        assertSafeTableName(tableName);
        if (!tableExists(tableName)) {
            throw new ReceiptException(HttpStatus.NOT_FOUND, "RECEIPT_NOT_FOUND", "指定されたレシートが見つかりません。");
        }

        String sql = "SELECT line_no, text FROM " + tableName + " ORDER BY line_no";
        List<ReceiptLine> lines = jdbcTemplate.query(sql, (rs, rowNum) ->
                new ReceiptLine(rs.getInt("line_no"), rs.getString("text"))
        );
        ReceiptSummary summary = summaryFor(tableName);
        return new ReceiptDetail(summary.tableName(), summary.lineCount(), summary.createdAt(), lines);
    }

    @Transactional
    public void deleteReceipt(String tableName) {
        assertSafeTableName(tableName);
        if (!tableExists(tableName)) {
            throw new ReceiptException(HttpStatus.NOT_FOUND, "RECEIPT_NOT_FOUND", "指定されたレシートが見つかりません。");
        }
        if (tableExists("receipt_structured_summary") || tableExists("receipt_structured_item")) {
            ensureStructuredDataTables();
        }
        jdbcTemplate.execute("DROP TABLE " + tableName);
        if (tableExists("receipt_structured_item")) {
            jdbcTemplate.update("DELETE FROM receipt_structured_item WHERE receipt_table_name = ?", tableName);
        }
        if (tableExists("receipt_structured_summary")) {
            jdbcTemplate.update("DELETE FROM receipt_structured_summary WHERE receipt_table_name = ?", tableName);
        }
        ensureImageHashRegistry();
        jdbcTemplate.update("DELETE FROM receipt_image_hash_registry WHERE table_name = ?", tableName);
    }

    private List<String> findReceiptTableNames() {
        return jdbcTemplate.queryForList(
                        "SELECT LOWER(table_name) FROM information_schema.tables " +
                                "WHERE LOWER(table_schema) = 'public' AND LOWER(table_name) LIKE 'receipt_%' " +
                                "ORDER BY table_name DESC",
                        String.class
                ).stream()
                .filter(ReceiptTableName::isSafe)
                .toList();
    }

    private ReceiptSummary summaryFor(String tableName) {
        String sql = "SELECT COUNT(*) AS line_count, MAX(created_at) AS created_at FROM " + tableName;
        return jdbcTemplate.queryForObject(sql, (rs, rowNum) -> new ReceiptSummary(
                tableName,
                rs.getInt("line_count"),
                rs.getObject("created_at", OffsetDateTime.class)
        ));
    }

    private boolean tableExists(String tableName) {
        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM information_schema.tables " +
                        "WHERE LOWER(table_schema) = 'public' AND LOWER(table_name) = LOWER(?)",
                Integer.class,
                tableName
        );
        return count != null && count > 0;
    }

    static void assertSafeTableName(String tableName) {
        if (!ReceiptTableName.isSafe(tableName)) {
            throw new ReceiptException(HttpStatus.INTERNAL_SERVER_ERROR, "UNSAFE_TABLE_NAME", "安全でないテーブル名が生成されました。");
        }
    }
}
